name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Check formatting
        shell: pwsh
        run: |
          Write-Host "Check formatting"
          cargo fmt --all -- --check

          if ($LastExitCode -eq 1) {   
            throw "Bad formatting, please run 'cargo +stable fmt --all'"
          }
  lints:
    name: Run rust-clippy analyzing
    runs-on: ubuntu-18.04
    needs: formatting
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

  build:
    name: picky ${{ matrix.type }} [${{ matrix.os }}]
    runs-on: ${{ matrix.runner }}
    needs: formatting
    strategy:
      fail-fast: false
      matrix:
        os: [ windows, linux ]
        type: [ build, test ]
        include:
          - os: windows
            runner: windows-2019
          - os: linux
            runner: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Configure runner
        if: matrix.os == 'linux'
        run: |
          sudo apt update
          sudo apt install python3-wget python3-setuptools

      - name: Build [${{ matrix.os }}]
        if: matrix.os == 'linux' && matrix.type == 'build'
        run: cargo build --release

      - name: Build [${{ matrix.os }}]
        if: matrix.os == 'windows' && matrix.type == 'build'
        env:
          RUSTFLAGS: '-C target-feature=+crt-static'
        run: cargo build --release --target=x86_64-pc-windows-msvc

      - name: Test [${{ matrix.os }}]
        if: matrix.type == 'test'
        run: cargo test --release --features "wincert","ctl","pkcs7"

      - name: Prepare artifacts
        id: prepare-artifacts
        if: matrix.type == 'build'
        shell: pwsh
        run: |
          $StagingDir = Join-Path "$Env:RUNNER_TEMP" "picky"
          $ArchDir = Join-Path $StagingDir "${{matrix.os}}" "x86_64"
          New-Item -Path $ArchDir -ItemType "directory"

          $Binaries = @("picky-server", "picky-signtool")

          if ($Env:RUNNER_OS -Eq "Windows") {
            $Binaries = $Binaries | ForEach-Object {"$_.exe"}
          }

          Get-ChildItem -Recurse -Include $Binaries -File  | % {
            Copy-Item -Path $_.FullName -Destination $ArchDir -Force 
          }

          echo "::set-output name=staging-dir::$StagingDir"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: matrix.type == 'build'
        with:
          name: picky
          path: ${{ steps.prepare-artifacts.outputs.staging-dir }}

  msrv:
    # Minimum supported Rust version check for published crates.
    # If this break, bump crate version minor number.
    # See https://github.com/Devolutions/picky-rs/issues/89
    name: Check minimum rust version
    runs-on: ubuntu-18.04
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Configure runner 
        run: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain 1.56

      - name: cargo check picky-asn1
        continue-on-error: true
        run: cargo +1.56 check -p picky-asn1

      - name: cargo check picky-asn1-der
        continue-on-error: true
        run: cargo +1.56 check -p picky-asn1-der

      - name: cargo check picky-asn1-x509
        continue-on-error: true
        run: cargo +1.56 check -p picky-asn1-x509

      - name: cargo check picky
        continue-on-error: true
        run: cargo +1.56 check -p picky
